### ISSUE TITLE
Ошибка получения MessageContext

### ISSUE THREAD

**Issue by Donomas** [nitreojs/puregram#102]
ошибка возникает когда человек оставляет в чате сообщения в ответ на пост в канале.
 
 такое сообщение не отобразится в update из-за Error [ERR_INTERNAL_ASSERTION]: TypeError: Cannot read properties of undefined (reading 'type')
 
 Временное решение:
 - /** Information about the original message for forwarded messages */
    get forwardOrigin() {
        const { forward_origin } = this.payload;
        if (!forward_origin) {
            return;
        }
        if (!this.payload?.origin?.type) {
            return;
        }

**Comment by nitreojs** [comment]
дубликат https://github.com/nitreojs/puregram/issues/97

**Comment by nitreojs** [comment]
скоро будет выкачен в прод
