### ISSUE TITLE
sendMediaGroup ignores additional API params

### ISSUE THREAD

**Issue by groupunknown** [nitreojs/puregram#103]
I started using puregram recently (yesterday) and I'm trying to migrate the method I used in telegraf, where when forwarding a media group to the bot it would send the media to some channels.

I've tried several different ways but I always end up getting the error TypeError: Cannot read properties of undefined (reading 'thumb')

I'm not an expert, so I'd like to know what I'm doing wrong.

```
const getFilesInMediaGroup = async (attachments) => {
    const extractedMedia = [];
    attachments.forEach(attachment => {
        if (attachment.mimeType && attachment.mimeType.slice(0, attachment.mimeType.lastIndexOf('/')) == 'video') {
            //extractedMedia.push(InputMedia.video(MediaSource.fileId(attachment.fileId)))
            extractedMedia.push({
                media: attachment.fileId,
                type: 'video',
                caption: "**My caption\\!**",
		parse_mode: "MarkdownV2",
            });
        }
        if (attachment.bigSize) {
            //extractedMedia.push(InputMedia.photo(MediaSource.fileId(attachment.bigSize.fileId)))
            extractedMedia.push({
                media: attachment.bigSize.fileId,
                type: 'photo',
            });
        }
    });
    return extractedMedia;
}

bot.updates.on('message', async (context) => {
    if (context.isMediaGroup()) {
        let chat_id = '-100******';
        let mediaGroup = await getFilesInMediaGroup(context.mediaGroup.attachments);
        bot.api.sendMediaGroup(chat_id, mediaGroup, {});
        //bot.api.call('sendMediaGroup', { chat_id, mediaGroup });
    }
});
```

**Comment by nitreojs** [comment]
first of all, in `puregram` we don't call api like this:
> ```js
> bot.api.sendMediaGroup(chat_id, mediaGroup, {});
> ```

in all `.api` methods there's only one singular argument, and that's an object defined by the [telegram bot api documentation](https://core.telegram.org/bots/api) that you need to pass. so we should start from that:
```js
bot.api.sendMediaGroup({
  chat_id,
  media: mediaGroup,
  ...
})
```

secondly, since you're using that api method inside of updates handler, you get this fancy new `context` variable ([what are contexts?](https://github.com/nitreojs/puregram?tab=readme-ov-file#what-are-contexts)), and with contexts you can call api methods much more easily!
```js
context.sendMediaGroup(mediaGroup)
```

these two code snippets above are identical!

now, as [mentioned in readme](https://github.com/nitreojs/puregram?tab=readme-ov-file#sending-input-media), it's easier to use `InputMedia` class rather than manually creating these objects for methods like `sendMediaGroup` or `editMessageMedia`. seems like you've already tried this method but commented it out for some reason 🤷 

what you need to do is simply to do this:

```js
const mediaGroup = attachments.map((attachment) => {
  if (attachment.mimeType && attachment.mimeType.slice(0, attachment.mimeType.lastIndexOf('/')) == 'video') {
    return InputMedia.video(
      MediaSource.fileId(attachment.fileId),
      { caption: '**My caption\\!**', parse_mode: 'MarkdownV2' }
    )
  }
  
  return InputMedia.photo(
    MediaSource.fileId(attachment.bigSize.fileId)
  )
})
```

###### via `.api`
```js
bot.api.sendMediaGroup({
  chat_id,
  media: mediaGroup
})
```

###### via `context` methods
```js
context.sendMediaGroup(mediaGroup)
```

**Comment by groupunknown** [comment]
Thank you very much for the help, the examples are much simpler and cleaner than the telegraf, which I have been using for months.

Even though it worked, I'm still having trouble sending the group with the caption and keeping the options that come in the captionEntities, using the example you provided bot.api.sendMediaGroup() I couldn't send the media group with the original caption.

I'm adding the caption only in the first item of the group, even with something simple as you can see below, it still doesn't work.

```
const mediaGroup = context.mediaGroup.attachments.map((attachment) => {
    if (attachment.mimeType && attachment.mimeType.slice(0, attachment.mimeType.lastIndexOf('/')) == 'video') {
        return InputMedia.video(
            MediaSource.fileId(attachment.fileId)
        )
    }
    return InputMedia.photo(
        MediaSource.fileId(attachment.bigSize.fileId)
    )
});

mediaGroup[0].caption = 'teste';
mediaGroup[0].parse_mode = 'MarkdownV2';

bot.api.sendMediaGroup({
    chat_id,
    media: mediaGroup
})
```

I've tested 'markdown' and 'markdownv2' but it doesn't work.

Is it possible to keep the original caption when sending the new media group?

**Comment by nitreojs** [comment]
i'm not sure this is a good way to set the caption:
> ```js
> mediaGroup[0].caption = 'teste';
> mediaGroup[0].parse_mode = 'MarkdownV2';
> ```

as for myself, i myself was using index of an array to determine if i should put caption or not. something like this:

```js
const mediaGroup = context.mediaGroup.attachments.map((attachment, index) => {
    if (attachment.mimeType && attachment.mimeType.slice(0, attachment.mimeType.lastIndexOf('/')) == 'video') {
        return InputMedia.video(
            MediaSource.fileId(attachment.fileId),
            { caption: index === 0 ? '... caption', parse_mode: 'Markdown' }
        )
    }
    return InputMedia.photo(
        MediaSource.fileId(attachment.bigSize.fileId)
    )
});
```

that's if you need a caption only on videos that are first in the group, you could do the same for the `InputMedia.photo` below and it should work!

**Comment by groupunknown** [comment]
Even following the example still doesn't work, for some reason it seems that the caption is ignored while sending.

**Comment by nitreojs** [comment]
in telegram open each media element and see if there is a caption in at least one of them, or maybe there are multiple captions? are you sure the first element of the media group is a video?

**Comment by groupunknown** [comment]
My channel follows a pattern in all content, videos are always uploaded first and the description only appears on the first item.

I've done several tests following the examples you went through, I've tested forwarding several different content and with different descriptions and it still doesn't work.

Only the media are sent by sendMediaGroup, even following the examples, it seems to me that the api is ignoring the caption during the sending.

**Comment by nitreojs** [comment]
could you please provide your current code? so it's closer and easier for me to replicate
it may be a bug though, i might have broken smth with the latest commit =D

**Comment by groupunknown** [comment]
```
const captionMark = {
    caption: 'teste',
    parse_mode: 'markdown'
}
const mediaGroup = context.mediaGroup.attachments.map((attachment, index) => {
    if (attachment.mimeType && attachment.mimeType.slice(0, attachment.mimeType.lastIndexOf('/')) == 'video') {
        return InputMedia.video(
            MediaSource.fileId(attachment.fileId),
            index === 0 ? captionMark : ''
        )
    }
    return InputMedia.photo(
        MediaSource.fileId(attachment.bigSize.fileId),
        index === 0 ? captionMark : ''
    )
});
console.log(mediaGroup);
```

Result:
```
[
    {
        type: 'video',
        media: {
            type: 'file_id',
            value: 'BAACAgEAA...'
        },
        caption: 'teste',
        parse_mode: 'markdown'
    },
    {
        type: 'photo',
        media: {
            type: 'file_id',
            value: 'AgACAgEAAxkBA...'
        }
    }
]
```

**Comment by nitreojs** [comment]
oh yeah and you're using the latest `puregram` version right? the `2.26.0` one

**Comment by groupunknown** [comment]
Yes

**Comment by nitreojs** [comment]
can confirm, this is definitely a bug, will fix in about an hour or so. thanks!!

**Comment by nitreojs** [comment]
_by "an hour" i definitely meant an actual hour 😄_
