### ISSUE TITLE
Бот перестал реагировать в группах.

### ISSUE THREAD

**Issue by depre33edBoy** [nitreojs/puregram#108]
Вчера у меня в официальной беседе, был большой наплыв новых пользователей, пользователи начали активно писать сообщения, сначала были лимиты, потом вообще перестало обрабатывать сообщения от них и никакие ошибки не выходили. У меня все прекрасно работает, а у других людей нет почему-то, думал проблема в моем коде, но в ЛС у других пользователей как оказалось все работает, плюс когда пользователи используют инлайн-кнопки, после моего ввода команды, у них он откликается, в чем может быть причина?

**Comment by nitreojs** [comment]
не совсем ясна проблема, это могла быть проблема с bot api - попробуй перевыпустить токен; попробуй настроить логгеров при каждом действии и смотреть, когда перестает обрабатывать, так хотя бы узнаем где может возникать ошибка

**Comment by depre33edBoy** [comment]
Благодарю за отзывчивость, проблема была решена!
