### ISSUE TITLE
Нет обработки необязательных полей в chat-shared

### ISSUE THREAD

**Issue by OGLwqx** [nitreojs/puregram#110]
## the bug
https://github.com/nitreojs/puregram/blob/df9c145ba003e59f617fdc8d4037c2d1e21200b4/packages/puregram/src/contexts/chat-shared.ts#L55

## expected behavior
Контекст должен возвращать все поля события, включая title, username, photo при их наличии

## environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.26.2` |
| `node`          | `latest` |
| `TypeScript`    | `latest` |
| `yarn` or `npm` | `latest` |

## additional context
В [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat) есть необязательные поля:

| Field         | Type | Description |
| :-----------:   | :-----: |:-----: |
| request_title      | Boolean | Optional. Pass True to request the chat's title |
| request_username     | Boolean | Optional. Pass True to request the chat's username |
| request_photo     | Boolean | Optional. Pass True to request the chat's photo |

При передаче в них true в объекте также возвращаются title, username, photo, которые никак не обрабатываются в контексте

**Comment by nitreojs** [comment]
и правда. как-то упустил при создании этого контекста. в течение получаса добавлю и пушну фикс, спасибо!

**Comment by nitreojs** [comment]
я 20 минут думал над названием коммита просто

**Comment by nitreojs** [comment]
стоп а `sharedPhoto` бляяя ща

**Comment by nitreojs** [comment]
теперь кайфарик
