### ISSUE TITLE
[Bug] Не выбрасывается ошибка при неудачной попытке получения данных о боте

### ISSUE THREAD

**Issue by MrZillaGold** [nitreojs/puregram#28]
## The bug
Если при подключении к LongPoll не удалось получить информацию о боте (например Telegam заблокирован у оператора, либо любая другая причина), то промис startPolling не выбрасывает соответственную ошибку.

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.1.0` |
| `node`          | `16.4.1` |
| `TypeScript`    | `4.3.2` |
| `yarn` or `npm` | `7.18.1` |

## Additional context
https://github.com/nitreojs/puregram/blob/master/packages/puregram/src/updates.ts#L342-L348

**Comment by nitreojs** [comment]
https://github.com/nitreojs/puregram/commit/4e5b17206b5ee3423cb7c11f7bcdcf99a9d56208 был также задействован
