### ISSUE TITLE
change default branch name

### ISSUE THREAD

**Issue by evtn** [nitreojs/puregram#32]
**Is your feature request related to a problem? Please describe.**
THERE is a PROBLEm. 
Right now, default branch called 'lord'. That's not a problem.
Problem is that it's not called 'megatron'? thanks.

**Describe the solution you'd like**
Call ~~911~~ the default branch megatron.

**Describe alternatives you've considered**
Or maybe kuulilennuteetunneliluuk

**Additional context**
I also like bananas.

**Comment by m4l3vich** [comment]
+1 for kuulilennuteetunneliluuk
I like bananas as well

**Comment by evtn** [comment]
I think package should have bananas

**Comment by m4l3vich** [comment]
Let's discuss only default branch's name for now

**Comment by evtn** [comment]
> Let's discuss only default branch's name for now

Yes I agree. By the way, do you also like watermelons? Just curious. 
Sorry for bananas.
That's surely off-topic. But watermelons, on the other hand...

Edit: thx for 1 like guys that's incredible
Edit 2: Wow epic 2 likes that's my record

**Comment by tailsjs** [comment]
+1
We need new name.
I suggest "makaronigram"

**Comment by nitreojs** [comment]
@evtn this can lead to big problems in the whole world. here's why:
1. there wouldn't be any `lord` anymore, that's a thing
2. `lord` also likes bananas, so why not keep `lord` instead?
3. **bananas**

no rename `lord` to `megatron` or even `kuulilennuteetunneliluuk`. also stop posting about ~~amongus~~ bananas and watermelons

**Comment by evtn** [comment]
> @evtn this can lead to big problems in the whole world. here's why:
> 
>     1. there wouldn't be any lord anymore, that's a thing
> 
>     2. lord also likes bananas, so why not keep lord instead?
> 
>     3. bananas
> 
> 
> no rename lord to megatron or kuulilennuteetunneliluuk. also stop posting about ~amongus~ bananas and watermelons

Damn, dude, chill. Don't you like bananas? I mean we could make some sort of banana thread here so people would come for bananas and see your package you will get famous free

**Comment by m4l3vich** [comment]
> > Let's discuss only default branch's name for now
> 
> Yes I agree. By the way, do you also like watermelons? Just curious.
> Sorry for bananas.
> That's surely off-topic. But watermelons, on the other hand...

Watermelons are good, but personally I think that mirza melons are better.

**Comment by nitreojs** [comment]
_what the fuck is this issue even_

**Comment by nitreojs** [comment]
no renaming lord to megatron because my mom will be crying. closed

**Comment by evtn** [comment]
Sad. Still, I have a banana, that's nice.
Goodbye
