### ISSUE TITLE
HTML methods do escape chars, but they should not

### ISSUE THREAD

**Issue by nitreojs** [nitreojs/puregram#39]
yes

**Comment by raywave** [comment]
example: 

```js
const { HTML } = require('puregram')

console.log(HTML.bold(`bold + ${HTML.italic('italic')}`))
// should return: <b>bold + <i>italic</i></b>
// actually returns: <b>bold + &lt;i&gt;italic&lt;/i&gt;</b>
```

**Comment by nitreojs** [comment]
@nitreojs might be false positive since any parse mode class’ methods are made to escape any character which needs an escape. so you can expect to put any dangerous value into any parse mode class method and be ready for it to be parsed correctly without any error

**Comment by nitreojs** [comment]
assuming as false positive; possibly will return back later
