### ISSUE TITLE
when I call the telegram.updates.StartPolling() function I get an error

### ISSUE THREAD

**Issue by Zajroid** [nitreojs/puregram#65]
## Steps to reproduce
1. I take the current from dotenv insert it into Telegram.FromToken(proccess.env.TOKEN)
2. when I call the telegram.updates.StartPolling() function I get an error: unable to fetch bot data from the start

## Expected behavior
started bot

## Screenshots
https://pastenow.ru/6024c955b2e8921638db5d9033d5219e

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `^2.8.2` |
| `node`          | `14.20.0` |
| `TypeScript`    | `not use` |
| `yarn` or `npm` | `npm` |

**Comment by nitreojs** [comment]
that's not actually a bug; in fact, that's a feature: `puregram` was not able to fetch [getMe](https://core.telegram.org/bots/api#getme) due to some error and thus failed the polling initialization. perhaps something is wrong with your connection with api.telegram.org?
you may also enable debug (how? [here](https://github.com/nitreojs/puregram#how-do-i-enable-debugging)) and see what exactly is going wrong

**Comment by Zajroid** [comment]
puregram:updates:startPolling fetching bot data... +0ms
  puregram:updates:startPolling unable to fetch bot info, perhaps no internet connection? +2ms


telegram requests work, here is a screenshot of how I try to use your library:
https://pastenow.ru/6024c955b2e8921638db5d9033d5219e

**Comment by nitreojs** [comment]
> puregram:updates:startPolling fetching bot data... +0ms puregram:updates:startPolling unable to fetch bot info, perhaps no internet connection? +2ms
> 
> telegram requests work, here is a screenshot of how I try to use your library: https://pastenow.ru/6024c955b2e8921638db5d9033d5219e

> you may also enable debug (how? [here](https://github.com/nitreojs/puregram#how-do-i-enable-debugging)) and see what exactly is going wrong

**Comment by nitreojs** [comment]
closing the issue since no response was given, assuming you fixed the problem. if you didn't, feel free to reopen the issue
