### ISSUE TITLE
ctx.sendVoice возвращает ошибку при MediaSource.buffer(audio)

### ISSUE THREAD

**Issue by tailsjs** [nitreojs/puregram#72]
## The bug
При передаче в ctx.sendVoice буфера аудио через MediaSource.buffer, либа выдаёт ошибку

## Steps to reproduce
1. Получить буфер аудио (любого)
2. `ctx.sendVoice(MediaSource.buffer(audioBuffer))`

## Expected behavior
Бот отправит голосовое сообщение с нужным мне аудио.

## Screenshots
![image](https://user-images.githubusercontent.com/49571184/215747750-3c6a5d42-54f8-4671-a764-b36919eadebf.png)

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.9.8` |
| `node`          | `16.16.0` |
| `yarn` or `npm` | `8.11.0` |

**Comment by nitreojs** [comment]
ща разберемся ебать

**Comment by nitreojs** [comment]
```ts
import { fetch } from 'undici'

import { MediaSource, Telegram } from './packages/puregram/src'

const telegram = Telegram.fromToken('4')

telegram.updates.on('message', async (context) => {
  const response = await fetch('ебейшая ссылочка')
  const arrayBuffer = await response.arrayBuffer()
  const buffer = Buffer.from(arrayBuffer)

  return context.sendAudio(MediaSource.buffer(buffer, { filename: 'song.mp3' }))
})

telegram.updates.startPolling()
```

![image](https://user-images.githubusercontent.com/40319427/224514650-eb5575c3-8eaa-408d-8cad-95bcc22c2bae.png)

UPD. arrayBuffer->buffer conversion чисто для проверки, изначально тестил `ArrayBuffer`

**Comment by tailsjs** [comment]
Тестил на обновлённой версии модуля. Всё то же самое.

```js
const { Telegram, MediaSource } = require("puregram");
const YandexAliceClient = require("yandex-alice-client")

const bot = new Telegram({
    token: '2'
});

const client = new YandexAliceClient.default();
await client.connect();

bot.updates.on('message', async(ctx) => {
 const response = await client.sendText("Hello world!", { isTTS: true })
 ctx.sendVoice(MediaSource.buffer(response.audio), { title: "bot.ogg", reply_to_message_id: ctx.id })
})
```

**Comment by nitreojs** [comment]
fixed in https://github.com/nitreojs/puregram/commit/8c5665cce482ada67bf3eeb27e9760968b47226e
