### ISSUE TITLE
При { parse_mode: 'markdownv2' } и при использовании точки в сообщении вылетает ошибка.

### ISSUE THREAD

**Issue by tailsjs** [nitreojs/puregram#77]
## The bug
При { parse_mode: 'markdownv2' } и при использовании точки в сообщении вылетает ошибка.

## Steps to reproduce
![image](https://github.com/nitreojs/puregram/assets/49571184/2925fcb6-d5be-433a-a131-e567707d9482)

## Expected behavior
Отправка сообщения с жирным текстом.

## Screenshots
![image](https://github.com/nitreojs/puregram/assets/49571184/1c249a79-3986-4dd6-b7f9-1a0b88ce23d9)

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.11.0` |
| `node`          | `16.16.0` |
| `TypeScript`    | `NOT_USED` |
| `yarn` or `npm` | `8.11.0` |

## Additional context
critical баг исправьте пж он ломает систему защиты майкрософт

**Comment by evtn** [comment]
Потому что точка это зарезервированный символ в mdv2

**Comment by tailsjs** [comment]
а кек справедливо

**Comment by nitreojs** [comment]
спасибо
