### ISSUE TITLE
Устаревшая документация или примеры.

### ISSUE THREAD

**Issue by titsex** [nitreojs/puregram#86]
Пытаюсь использовать @puregram/sessions, как любой разработчик, чтобы понять, как мне использовать тот или иной пакет, я полез в документацию.

Сначала я залез в examples/session.js, где используется SessionManager и встроенный middleware, но так как я работаю с typescript, перешел в packages/session и там уже в README видимо старая вариация использования сессий, ведь импортируется из библиотеки какой-то метод session.

Собственно, вот examples/session:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/36f42991-8b57-4764-a22b-2d813b755932)

А вот packages/session:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/5ea2f30d-5ece-4125-ba91-f2b3c623509e)

У пару вопросов, которые исходя из различий в примерах и документации, я не понял:
1) могу ли я initial data как-то передать, чтобы не делать в событии message проверок, а иметь уже какие-то базовые значения.
2) что в качестве generic принимает SessionManager? Как я понял - он принимает тип/интерфейс/класс с данными которые будут хранится в сессии.
3) важен ли порядок обработки события message для SessionManager и HearManager (стоит ли что-то из них раньше друг-друга обрабатывать, или порядок не важен?)

**Comment by nitreojs** [comment]
сейчас забавно выходит - документация, лежащая в гитхаб невалидная, это невышедшая версия @puregram/session (за что извиняюсь, я думал, что смогу выложить ее раньше, но времени в обрез вааааще)
лучше смотри ту, что на [npm.puregram.cool/session](https://npm.puregram.cool/session), там она точно верная
та, что на гитхабе - будущая, когда я `@puregram/scenes` перепишу с нуля
извиняюсь за недопонимания!!!

**Comment by titsex** [comment]
Спасибо. Но там лишь javascript пример, про generic и initial data вопросы остаются.

**Comment by nitreojs** [comment]
насчет вопросов:
- в текущей версии максимум как можно сделать так это прокинуть мидлварь которая проверяет наличие context.session.foo...
- эээээ насколько я помню тип обьекта в самом session, то есть `SessionManager<T>` -> `context.session: T`
- в кейсе именно session + hear неважно, так как они друг от друга не зависят. но например если бы ты юзал session + scenes, тогда обязательно нужно было бы вызывать мидлвари session ДО мидлварей scenes (потому что scenes базируются на session)

**Comment by nitreojs** [comment]
из-за первого пункта (да и из-за того, что классы в таких библиотеках ненужны, потому что их постоянно надо инициализировать) я и начал переписывать с нуля =)

**Comment by nitreojs** [comment]
> эээээ насколько я помню тип обьекта в самом session, то есть `SessionManager<T>` -> `context.session: T`

извините я вас обманул, он влияет только на `getStorageKey` параметр:

![image](https://github.com/nitreojs/puregram/assets/40319427/5b4285a4-e8a2-40b0-a8c0-73ccd1c2e624)

**Comment by titsex** [comment]
И еще, в старой документации наглядно показана типизация контекста. Там был SessionLayer, которого ныне нет.
![изображение](https://github.com/nitreojs/puregram/assets/61911688/6540a514-7709-426d-a1cb-234819f5c3fc)

Как теперь мне типиизровать контекст?

```typescript
interface ISessionData {
    counter: number
}

type CustomContextType = MessageContext & { session: ISessionData }
```

Это будет правильным решением?

А так, буду в дальнейшем ожидать новых версий.
Предпочтительно видеть бы в них встроенную проверку на наличия хранимых данных и прокидывание изначальных.

Аля как-то так:

```typescript
interface ISessionData {
    counter: number
}

const sessionManager = new SessionManager<ISessionData>({
    initial: {
        counter: 0
    }
})

telegram.updates.on('message', context => {
    console.log(context.session.counter) // 0
})
```

**Comment by nitreojs** [comment]
> Как теперь мне типиизровать контекст?

я обычно делал так:

```ts
import type { Context } from 'puregram'
import type { SessionInterface } from '@puregram/session'

interface SessionAddition {
  counter: number
}

export type ModernContext<C extends Context> = C & SessionInterface & { session: SessionAddition }
``` 

ваще неинтуитивно согласен, по этой причине я и решил всё с нуля накодить, в новой-то версии (к слову, ее можно выкатить я думаю, че ей простаивать в гитхабе онли) `SessionLayer` для красоты сделан

> Предпочтительно видеть бы в них встроенную проверку на наличия хранимых данных и прокидывание изначальных.
> 
> Аля как-то так:
> 
> ```ts
> interface ISessionData {
>     counter: number
> }
> 
> const sessionManager = new SessionManager<ISessionData>({
>     initial: {
>         counter: 0
>     }
> })
> 
> telegram.updates.on('message', context => {
>     console.log(context.session.counter) // 0
> })
> ```

выглядит вкусно до тех пор, пока понимаешь, что чтобы такую типизацию завезти нужно делать чейнинг =)
типа такого:

```ts
const telegram = Telegram.fromToken('...')
  .load(new SessionManager())
  .load(new SomethingElse())
```

в таком случае в `telegram` сохранятся все нужные типы и будет всякий дефолтный тип указываться автоматически

а так я с радостью такое сделал бы, ибо текущая (новая) реализация просто вызывает `declare module 'puregram' { ... }`, там никак не передать никакой `T` (а других вариантов решения я не вижу, чтобы сразу показывался `context.session`)

**Comment by titsex** [comment]
Думаю с этим можно поэксперементировать.

Вообще интуитивно понятно было бы если бы пакет экспортировал свой конекст, принимающий дженериком тип хранимых в сессии данных.

В таком случаи думаю большинство даже в документацию не лезло бы.

Аля:
```typescript
import { SessionContext, SessionManager } from '@puregram/session'
import { MessageContext, Context } from 'puregram'

interface ISessionData {
    counter: number
}

type ContextType<C extends Context> = C & SessionContext<ISessionData>
type ModernContext = ContextType<MessageContext>

const sessionManager = new SessionManager<ISessionData>()

telegram.updates.on('message', (context: ModernContext) => {
    if (!('counter' in context.session)) context.session.counter = 0
    else context.session.counter++
    
    console.log(context.session.counter) // 1
})
```

А в купе с предыдущим моим предложением (хоть я и понял, что это очень сложно), выглядело бы это еще вкуснее:
```typescript
import { SessionContext, SessionManager } from '@puregram/session'
import { MessageContext, Context } from 'puregram'

interface ISessionData {
    counter: number
}

type ContextType<C extends Context> = C & SessionContext<ISessionData>
type ModernContext = ContextType<MessageContext>

const sessionManager = new SessionManager<ISessionData>({
    initial: {
        counter: 0
    }
})

// Или вовсе если не будет других опций у SessionManager-а, initial data опрокинуть сразу в конструкторе:
/*
const sessionManager = new SessionManager<ISessionData>({
    counter: 0
})
*/

telegram.updates.on('message', (context: ModernContext) => {
    context.session.counter++
    
    console.log(context.session.counter) // 1
})
```

**Comment by nitreojs** [comment]
> ```ts
> const telegram = Telegram.fromToken('...')
>   .load(new SessionManager())
>   .load(new SomethingElse())
> ```

ща посидел покумекал, пришла в голову идея на все модули накинуть какой нибудь `extension` экспорт, а в самом `Telegram` сделать `.extends(Extended)`, чтобы получилось что-то такое:

```ts
import { extension } from '@puregram/session'

const telegram = Telegram.fromToken('...')
  .extends(extension<SessionInitial>())
```

причем `extension` является буквально пустой функцией, просто для выведения типов... надо над этим подумать

**Comment by nitreojs** [comment]
> import { SessionContext, SessionManager } from '@puregram/session'

если говорить о текущей версии `@puregram/session` в npm, то печальные новости

![image](https://github.com/nitreojs/puregram/assets/40319427/90ae0b35-74d1-4d41-ba08-86fb8fd1f923)

если говорить о новой, то это и есть `SessionLayer` же (в новых версиях модулей я буду везде использовать `*Layer` для упрощения и стабилизации), нет?

![image](https://github.com/nitreojs/puregram/assets/40319427/0a7359c4-0a45-44b1-b22a-45c8b0d3e436)

или имеется в виду отдельный экспортируемый тип, который по дефолту делает `C & { session: T }`? не очень понимаю, как это можно реализовать, правда...

**Comment by titsex** [comment]
Про SessionLayer и имел ввиду. Я к слову так и не понял, что у тебя новая, а что старая версия.

Вроде hear реализован как класс, а "новый"(?) session экспортирует middelware для telegram.updates.use()

**Comment by nitreojs** [comment]
ахахаха, согласен, тут путаница дикая, давай так обьясню:

то, что сейчас на npm (то есть то, что ты скачиваешь) - старые версии, они все с классами (потому что подход с классами выглядел прикольно тогда, 3-4 года назад)

то, что сейчас на гитхабе ИСКЛЮЧИТЕЛЬНО у @puregram/session (функциональное) - новая версия, она НЕ в релизе, потому что я хотел еще и @puregram/scenes переписать чтобы избавиться от классов, и тогда оба выкатить

**Comment by titsex** [comment]
Всё, понял.

Да действительно, кучу инстансов классов не очень красиво, учитывая всё окружение puregram. С миддлваринами было бы удобнее. Поддерживаю твоё решение.

**Comment by nitreojs** [comment]
ура! рад слышать =)

когда появится мнооого много времени (а то ща завалы по учебе), может и смогу допилить всё на функциональщину для красоты и удобства. а пока получается вот такой вот комок туда-сюда-обратно =(

**Comment by titsex** [comment]
Еще вопрос появился. При использовании hearManager, он поглащает другие события message, если сообщение = команда?

Вопрос звучит запутанно, поэтому поясню:
Есть команда start, она в коде обрабатывается ниже чем событие message, но логи с события message я не получаю.

![изображение](https://github.com/nitreojs/puregram/assets/61911688/dbb3b5b2-40dc-4d50-b760-8b089b957e0c)

Событие message выше регистрации команд, но если отправить команду, придет лог только с нее.

сам модуль команды старт:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/484d33e0-53ce-4bf5-b816-5a8e3dcf4b56)

и собственно логи:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/5978abf0-25d9-4244-af3e-538e0e2b1831)

Твой пакет очень похож на vk-io, но что в vk-io, что в telegraf, если событие message было выше команд (у vk-io свой hearmanager тоже был), то оно отрабатывало. Более того, команды не срабатывали, пока в событии message, что выше обработчиков команд, не возвращался колбэк next()

**Comment by nitreojs** [comment]
> Есть команда start, она в коде обрабатывается ниже чем событие message, но логи с события message я не получаю.

middleware ж, чтобы цепочка продолжала выполнение, нужно вызывать `next()`:

```ts
telegram.updates.on('message', (context. next) => {
  console.log(context)
  
  return next()
})

telegram.updates.on('message', (context) => {
  console.log('hey there!!!')
})
```

**Comment by titsex** [comment]
Просто странное поведение. Про вызов некст я говорил, да.

Обычно оно работает наоборот =)

Аля команды зарегистрированны hearmanager-ом ниже чем обработчик событий. То есть лог 123 должен был быть, а команда должна была бы молчать, пока из события message, что ВЫШЕ обработчиков команд, не вернулся бы вызов next()

**Comment by nitreojs** [comment]
а, стоп, я понял о чем ты

`hearManager.middleware` выполняется раньше твоего `.on('message')`, потому и обрабатывается до `123` лога

**Comment by titsex** [comment]
И кстати, даже с next() получается тоже самое поведение.

Вот измененный код:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/04f824f8-34bf-49a3-8469-470eb6a8f8c3)

Вот логи:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/b7ff76ff-d81d-4f57-b6eb-73937c6d1de4)

То есть даже с next() не получаю эти 123.

**Comment by nitreojs** [comment]
а, стоп, НЕ получаешь? странно, ща гляну, воркает ли у меня

btw а это не странно ли, что ты называешь переменную в цикле `module`? это же оверрайд глобальной `module`, нет?... там точно всё правильно передается в `hear`?..

**Comment by nitreojs** [comment]
а ой я дурачье, я же сам сказал, что `hearManager.middleware` идет ПЕРЕД твоим `.on`, ну вот
у тебя в `callback` нет вызова `next()`, а значит, что когда `callback` команды выполняется, действие цепи прерывается, дальше вниз по цепочке она не идет
чтобы ты получил `123`, тебе в `callback` надо указать `next` и вызвать его в конце, как и говорилось

**Comment by titsex** [comment]
Я кажись ошибку понял свою.

![изображение](https://github.com/nitreojs/puregram/assets/61911688/d54d8454-f6ad-4fc8-ae7a-0403b37a7f37)

hearManager.middleware выше моего обработчика событий)

А насчет module - нет, всё окей.
Команды ведь регистрируются, и я когда писал /start, получал лог.

**Comment by titsex** [comment]
Спасибо вновь, за быстрые ответы. Пойду дальше внедрять остальную эко-систему puregram.

**Comment by titsex** [comment]
И снова привет. Перерыл всю документацию и не понял как получить ссылку на медиа.
В документации лишь примеры со скачиванием медиа, но получение ссылки - нет.

Сам нашел такой способ: context.telegram.getFileUrl(file_id), но возвращает он странную ссылку, перейдя по которой я получаю это:
![изображение](https://github.com/nitreojs/puregram/assets/61911688/e1fa91a0-9e1d-4ad3-ac7c-63736449721f)

ссылка формата: https://api.telegram.org/file/TOKEN/FILE_ID

**Comment by nitreojs** [comment]
`/file/bot[TOKEN]/...`, не забывай `bot`

**Comment by titsex** [comment]
Но ссылку ведь не я составил. Я методу getFileURL передал fileId и получил результатом некорректную ссылку.

**Comment by nitreojs** [comment]
@titsex не думаю, что такое может быть + getFileURL принимает именно path, который был получен из telegram.api.getFile({ file_id }).then(r => r.file_path)

**Comment by titsex** [comment]
То есть никаким образом, как в телеграфе, напрямую по файл айди нельзя получить её ссылку?

**Comment by nitreojs** [comment]
@titsex ну я могу сделать конечно метод который выдает именно ссылку на файл, если так будет удобнее и если ею кто то будет пользоваться

**Comment by titsex** [comment]
Просто в телеграфе абсолютно такой же метод, но он принимает файл айди, а не путь. Те кто перешли с телеграфа, точно запутаются.

**Comment by nitreojs** [comment]
@titsex накинул `getAttachmentURL` в https://github.com/nitreojs/puregram/commit/cddc1edfd35a3f66f2c48806c37624fcc86a4a0b, в некст минор/патч релизе будет

**Comment by titsex** [comment]
Спасибо большое!

Покажу обхожусь подобным:
![image](https://github.com/nitreojs/puregram/assets/61911688/60427e34-2e2b-4f96-ba08-89c43082c674)

Но согласись, это дополнительные лишние действия.
Я просто не нашел другого применения file_path, кроме как получение ссылки по нему.
И не понимаю зачем этот лишний этап.

Спасибо что учёл мнение, лучший!

**Comment by nitreojs** [comment]
@titsex суть getFileURL (как и file_path) как раз была в том, чтобы составить саму ссылку - чтобы тебе ручками не надо было ее собирать, на самом то деле
