### ISSUE TITLE
Типизация собственной реализации хранилища.

### ISSUE THREAD

**Issue by titsex** [nitreojs/puregram#87]
И снова привет. Пытаюсь в качестве storage использовать Redis. Пишу свой класс имплементирующий методы SessionStorage и натыкаюсь на некоторые проблемы с типами и отличие от того, что на гитхабе.

В [исходном коде на гитхабе,](https://github.com/nitreojs/puregram/blob/lord/packages/session/src/storages/storage.ts) интерфейс имеет правильную типизацию (так например, get метод возвращает any или undefined).
![image](https://github.com/nitreojs/puregram/assets/61911688/5a8a289b-1b5d-4c9f-90b1-13463e773506)

Но в актуальной версии типизация очень странная. Он ожидает объект (просто объект) или ничего.
![image](https://github.com/nitreojs/puregram/assets/61911688/44bdf38f-0ae0-4d5a-a138-fabde17a45cf)

И из-за этого приходится делать вот такие костыли =)
![image](https://github.com/nitreojs/puregram/assets/61911688/c77f7cab-c900-4ff9-8c79-705af8d793a8)

**Comment by nitreojs** [comment]
> Но в актуальной версии типизация очень странная

😄 опять проблемы текущей версии сессии; я недавно review'ил код и нихуя не понял, почему там object, поэтому в актуальной (новой) версии там any

**Comment by nitreojs** [comment]
к слову, [puregram-redis-storage](https://www.npmjs.com/package/puregram-redis-storage)!

**Comment by titsex** [comment]
Да, я сейчас костыль на костыле (as unknown as ...) делаю и для гета и для сета.

**Comment by titsex** [comment]
Видел, немного смутило что обновлений нет.
Да и свой класс не так то и сложно реализовать, и поддерживать будет проще.

**Comment by nitreojs** [comment]
а там обновлять то и нечево, session тоже необновленный лежит по факту, плюсом челики в форуме юзают говорят все работает и тема

**Comment by nitreojs** [comment]
короче видимо лучше новую версию session релизить а то чето жопа какаято

**Comment by titsex** [comment]
Было бы славно. Ибо сет метод ожидает value как object. Пытаясь привести к any, ругается линтер. Пришлось отключить для этой строчки его.

**Comment by titsex** [comment]
Что за метод touch и зачем он нужен? Я сначала увидел его, подумал что это какой-то переименованный has.
Полез в твой MemoryStorage и там реализация отсутствует:
![image](https://github.com/nitreojs/puregram/assets/61911688/4982eb00-861a-4360-adf2-6eee63862291)

Судя по типам, он ничего не возвращает:
![image](https://github.com/nitreojs/puregram/assets/61911688/2a380f69-4e91-471b-a9b6-c2ec2819381a)


Раз он ничего не возвращает и даже ты не реализовал его в MemoryStorage - зачем он?

**Comment by nitreojs** [comment]
действует так же как и `touch` в unix, а в `MemoryStorage` нет смысла его делать, все в памяти ж

**Comment by titsex** [comment]
Благодарю.

**Comment by nitreojs** [comment]
в ближайшее время релизну тогда @puregram/session пусть будет красивое удобное... ща времени просто нет допиливать @puregram/scenes

**Comment by titsex** [comment]
Спасибо за отзывчивость.
