### ISSUE TITLE
Сессии недоступны в других контекстах.

### ISSUE THREAD

**Issue by titsex** [nitreojs/puregram#88]
Снова здравствуй. Пытаюсь обработать данные из сессии в событии callback_query, то есть после нажатия кнопки.
Но как я понял, видимо это так и должно быть, сессии доступны только в событиях message, верно?
Тогда как работать с ними в других событиях? Например мне нужно выполнить действие связанное с сессией, после нажатия кнопки.

Обработчик:
![image](https://github.com/nitreojs/puregram/assets/61911688/cd5b79a7-0e75-4228-a53e-a87a308aacd3)

Событие:
![image](https://github.com/nitreojs/puregram/assets/61911688/ddd32cfd-b268-41e6-99bc-d3c310bb0cca)

Лог (context.session):
![image](https://github.com/nitreojs/puregram/assets/61911688/471cec22-90f0-4d63-8104-74a84c2381af)

**Comment by nitreojs** [comment]
> сессии доступны только в событиях message, верно?

неа, они доступны там, куда был прокинут `sessionManager.middleware`, в твоем случае - только у `message` . шоб и в `callback_query` можно было, ебани `telegram.updates.on(['message', 'callback_query'], sessionManager.middleware)`

**Comment by titsex** [comment]
Благодарю.

**Comment by nitreojs** [comment]
если чо напоминаю что в случае чего у нас есть [форум](https://forum.puregram.cool) в котором можно миллиард вопросов задавать в секунду и там я (и другие участники) будут отвечать быстрее!!
