### ISSUE TITLE
When i upload a file use Bun runtime i get AbortError

### ISSUE THREAD

**Issue by kravetsone** [nitreojs/puregram#89]
## The bug
When i upload a file use Bun runtime i get AbortError

```ts
import { MediaSource, Telegram } from "puregram";

const bot = Telegram.fromToken(
    ""
);

await bot.api
    .sendDocument({
        chat_id: -1001996532865,
        message_thread_id: 4,
        document: MediaSource.path(
            "some path",
        )
    })
```
I tried run it in Node and Bun. And when i run with node it's work
## Screenshots
![image](https://github.com/nitreojs/puregram/assets/57632712/5dbcc33d-2d8a-40a4-8c3d-d2442c086dda)

![image](https://github.com/nitreojs/puregram/assets/57632712/b1d64376-fe8c-4ce4-ad5b-0615f2df16a9)

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.23.1` |
| `TypeScript`    | `5.3.3` |
| `bun` | `1.0.17` |

**Comment by nitreojs** [comment]
as of now, puregram is not going to support neither bun nor deno because it is just not worth it, so the issue is kind of irrelevant to the repository. but if any of you insist (and/or need this), you might fork puregram and add bun support!
