### ISSUE TITLE
add @puregram/markup and @puregram/callback-data to ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by neverlane** [nitreojs/puregram#91]
сиська писька киска жопа

**Comment by nitreojs** [comment]
пиздато описал иссуй

**Comment by nitreojs** [comment]
W ft. https://github.com/nitreojs/puregram/commit/d334d16259fd45e65e693e27f8fbf7c2f918ed1e & https://github.com/nitreojs/puregram/commit/0b49ea66c9d978836deba10b1d265d41d5ef142e
