### ISSUE TITLE
Некорректная работа @puregram/markup

### ISSUE THREAD

**Issue by totoroterror** [nitreojs/puregram#94]
## The bug
Некорректная работа модуля @puregram/markup

## Steps to reproduce
```typescript
import { bold, code, format, italic, hooks as markupHooks } from '@puregram/markup'

telegram.useHooks(markupHooks())

const message = format`
    👻 ${bold`Команда не найдена!`}

    ❔ ${italic`Попробуйте ввести ${code`/start`}, чтобы начать заново!`}
`

await context.send(message)
```

## Expected behavior
Нормальное форматирование, не должно стрипать newline (afaik должно делать strip indent/s) и должно правильно расставлять entities.

## Screenshots
![image](https://github.com/nitreojs/puregram/assets/105948080/9de5efa2-bbf1-4c31-ad98-6797b7cfb49e)

## Environment
| package         | version |
| :-----------:   | :-----: |
| `@puregram/markup`      | `1.2.0` |
| `node`          | latest as of 04.01.2024 |
| `TypeScript`    | `5.3.3` |
| `yarn` or `npm` | latest as of 04.01.2024 |

**Comment by nitreojs** [comment]
бля наверное fixed в 1.3.0

**Comment by totoroterror** [comment]
ну заебись тогда

**Comment by nitreojs** [comment]
согл проверь корочн

**Comment by totoroterror** [comment]
чуть позже проверю отпишу либо можешь сам я доверяю твоим тестам

**Comment by nitreojs** [comment]
я сам себе не доверяю хули уж тут

**Comment by nitreojs** [comment]
![image](https://github.com/nitreojs/puregram/assets/40319427/f70ac672-195a-40e5-aaca-fc14fca2c5fb)
НОРМ ЕБАШИТ!!!!!!!!!!!!

**Comment by totoroterror** [comment]
заебись
